version: '3'

services:
  mirotalk:
    image: takesolve:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: takesolve
    hostname: takesolve
    volumes:
      - .env:/usr/src/app/.env:ro
    restart: unless-stopped
    ports:
      - "3000:3000"